### PR TITLE
Mmhus/mireg sireg fixes #2188, #2202, #2203

### LINKED ISSUE #2188: Better implementation to raise illegal instruction exception while accessing un-implemented index CSR via sireg(really vsireg) at VS-mode
SPIKE code:
```
void sscsrind_reg_csr_t::verify_permissions(insn_t insn, bool write) const {
  if (proc->extension_enabled(EXT_SMSTATEEN)) {
    if ((state->prv < PRV_M) && !(state->mstateen[0]->read() & MSTATEEN0_CSRIND))
      throw trap_illegal_instruction(insn.bits());
  }

  // Don't call base verify_permission for VS registers remapped to S-mode
  if (insn.csr() == address)
    csr_t::verify_permissions(insn, write);

  if (proc->extension_enabled(EXT_SMSTATEEN)) {
    if (state->v && !(state->hstateen[0]->read() & HSTATEEN0_CSRIND))
      throw trap_virtual_instruction(insn.bits());
  }

  ......

  csr_t_p proxy_csr = get_reg();
  if (proxy_csr == nullptr) {
    if (!state->v) {
      throw trap_illegal_instruction(insn.bits());
    } else {
      throw trap_virtual_instruction(insn.bits());
    }
  }
  proxy_csr->verify_permissions(insn, write);
}

```

ISA Spec:
> The behavior upon accessing vsireg* from M-mode or HS-mode, or accessing sireg* (really vsireg*)
> from VS-mode, while vsiselect holds a value that is not implemented at HS level, is UNSPECIFIED.
>  It is recommended that implementations raise an illegal-instruction exception for
> such accesses, to facilitate possible emulation (by M-mode) of these accesses.

I think it's better to raise illegal instruction while `nullptr` returned by '`get_reg()`'

### PR DESCRIPTION
**Pull request by mmhus**
Fixes for #2188, #2202, #2203 

/cc @Steven-Li-Xiaogang Could you give your input, I wasn't able to test everything. Maybe you could run your tests on this branch?

### CODE REVIEW

**Comment by mmhus** [comment]
The CI build for ubuntu is failing, but it seems like a clone issue, unrelated to the changes, perhaps someone can restart the job.

**Review by aswaterman — APPROVED** [review]
LGTM, thanks.

File: riscv/csr_init.cc [hunk 1]
```diff
@@ -80,6 +80,28 @@ void state_t::csr_init(processor_t* const proc, reg_t max_isa)
...
+      add_csr(CSR_MCYCLECFGH, std::make_shared<rv32_high_csr_t>(proc, CSR_MCYCLECFGH, mcyclecfg));
+      add_csr(CSR_MINSTRETCFG, std::make_shared<rv32_low_csr_t>(proc, CSR_MINSTRETCFG, minstretcfg));
+      add_csr(CSR_MINSTRETCFGH, std::make_shared<rv32_high_csr_t>(proc, CSR_MINSTRETCFGH, minstretcfg));
+    } else {
+      add_csr(CSR_MCYCLECFG, mcyclecfg);
+      add_csr(CSR_MINSTRETCFG, minstretcfg);
+    }
+    if (proc->extension_enabled_const(EXT_SMCDELEG)) {
+      if (xlen == 32) {
+        cyclecfg = std::make_shared<counter_proxy_csr_t>(proc, CSR_MCYCLECFG, csrmap[CSR_MCYCLECFG]);
```
Comment (Steven-Li-Xiaogang) [inline riscv/csr_init.cc]: @mmhus 
I think `cyclecfg/instretcfg` should not be declared as `counter_proxy_csr_t`, access permission of ` mcyclecfg` and `minstretcfg` are not under control of` mcounteren`, also a fault indirect CSR index (with formula `address & 31`),  indirect access to CSR_MCYCLECFG and CSR_MINSTRETCFG will cause exception by calling `verify_permissions`

File: riscv/csrs.cc [hunk 2]
```diff
@@ -1919,7 +1919,16 @@ void sscsrind_reg_csr_t::verify_permissions(insn_t insn, bool write) const {
 
   csr_t_p proxy_csr = get_reg();
   if (proxy_csr == nullptr) {
-    throw trap_illegal_instruction(insn.bits());
+    // An attempt from VS-mode to access any inaccessible sireg* causes virtual instruction exception when AIA is enabled
+    if (proc->extension_enabled_const(EXT_SMAIA)) {
+      if (state->prv == PRV_S && state->v) {
+        throw trap_virtual_instruction(insn.bits());
```
Comment (Steven-Li-Xiaogang) [inline riscv/csrs.cc]: @mmhus @aswaterman @ved-rivos
There is still one question: should be all indices which are not proxied be treated as inaccessible?
1. AIA spec only defines 0x30-0x3F and 0x70-0xFF (if no IMSIC) as inaccessible, and others are reserved (unimplemented)
2. Could a virtual instruction exception be raised, while an attempt from VS-mode to `sireg`* while `vsiselect` holds a reserved value (ex. 0x100)?
