### PR TITLE
Make misa.C writable again, even in presence of Zc* extensions

### LINKED ISSUE #1172: Alignment  when 'C'  in misa CSR is cleared by software
Whether jump to 0x10082 triggers misaligned exception when  'C' in misa CSR is disabled by software? 
The answer is yes before Zc* is supported. 
However,  Zca is implied by 'C', but Zca can work alone without 'C' enabled.  So this becomes a new problem:
Whether Zca is also disabled when 'C' is disabled?

### PR DESCRIPTION
**Pull request by aswaterman**
Builds on and supersedes #1176. See extensive discussion on that PR.  Fixes #1172.

`misa.C` is now writable whenever `C` is included in the ISA string.  When `misa.C` is writable, all Zc* extensions are also under its direct control.  (There is still no mechanism to individually disable Zc* extensions, nor is there a mechanism to disable Zc* extensions when `misa.C` is read-only).

cc @liweiwei90, who authored the first version of this

### CODE REVIEW

File: riscv/processor.h [hunk 1]
```diff
@@ -232,12 +232,17 @@ class processor_t : public abstract_device_t
...
   bool extension_enabled_const(isa_extension_t ext) const {
-    if (ext >= 'A' && ext <= 'Z')
+    if (ext >= 'A' && ext <= 'Z') {
       return state.misa->extension_enabled_const(ext);
-    else
-      return isa->extension_enabled(ext);  // assume this can't change
+    } else {
+      assert(!extension_dynamic[ext]);
+      extension_assumed_const[ext] = true;
+      return extension_enabled(ext);
```
Comment (liweiwei90) [inline riscv/processor.h:240]: This way seems not necessary now since extension_enabled_const(EXT_ZCMT) has been changed to  extension_enabled(EXT_ZCMT) in the previous commit and we can use dynamic extensions directly here (it can be initialized just from isa string).

Comment (aswaterman) [reply riscv/processor.h:240]: Right.  But I think it was @scottj97's intention to future-proof the implementation--which, given he was able to do without duplicating the complicated enable logic, makes sense to me.

File: riscv/processor.h [hunk 2]
```diff
@@ -304,6 +312,10 @@ class processor_t : public abstract_device_t
   bool check_triggers_icount;
   std::vector<bool> impl_table;
 
+  std::bitset<NUM_ISA_EXTENSIONS> extension_enable_table;
```
Comment (scottj97) [inline riscv/processor.h:316]: I would add a comment here: "Note: does not include single-letter extensions in misa"

**Review by scottj97 — CHANGES_REQUESTED** [review]
I would squash 54a4089f20390c86c1a356fefda1ebf31b24d93f back into ca6ef8e3eed702e928b12d4a6c9791a9e4d1f13c since that will keep everything working as intended at every step of the way. Also the commit message for 54a4089f20390c86c1a356fefda1ebf31b24d93f doesn't all make sense anymore so it can just be discarded (but maybe keep the comment about `mutable`).

**Comment by aswaterman** [comment]
OK.  Attempt number 6, or whatever we're on now :)

**Review by scottj97 — APPROVED** [review]
